name: Mock Integration Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'cdk/**'

jobs:
  mock-integ-test:
    name: Mock Integration Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cdk
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './cdk/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Setup Docker for ADOT and App containers
        uses: docker/setup-buildx-action@v3
      
      # サイドカーコンテナをセットアップ（テスト用のモックアウト）
      - name: Setup mock container infrastructure
        run: |
          mkdir -p ./mock-test
          echo "# Mock Directory for integ test environment" > ./mock-test/README.md
      
      # 統合テスト用にCanaryのアセットディレクトリを準備
      - name: Setup Canary assets
        run: |
          mkdir -p lib/assets/canary/nodejs/node_modules/nodejs/node_modules
          echo 'exports.handler = async () => { return "ok" };' > lib/assets/canary/nodejs/node_modules/nodejs/node_modules/index.js
      
      # 型チェックだけ行う（実際にスクリプトを実行しない）
      - name: Type check integration tests
        run: |
          # 実際のAWSデプロイなしで型チェック
          npx tsc -p tsconfig.json --noEmit
          echo "✅ TypeScript compilation check passed"